/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author Jason
 */
public class PanelMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }
    
    public void escuchar(ControladorPrincipal control){
        jBAjustes.addActionListener(control);
        jBPlay.addActionListener(control);
        jBSalir.addActionListener(control);
        jBStats.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBPlay = new javax.swing.JButton();
        jBStats = new javax.swing.JButton();
        jBAjustes = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_play_unp.png"))); // NOI18N
        jBPlay.setActionCommand("PlayMenu");
        jBPlay.setContentAreaFilled(false);
        jBPlay.setPreferredSize(new java.awt.Dimension(104, 114));
        jBPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_play_press.png"))); // NOI18N
        add(jBPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 136, -1, -1));

        jBStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_estadisticas_unp.png"))); // NOI18N
        jBStats.setActionCommand("StatsMenu");
        jBStats.setContentAreaFilled(false);
        jBStats.setPreferredSize(new java.awt.Dimension(104, 114));
        jBStats.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_estadisticas_press.png"))); // NOI18N
        add(jBStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 136, -1, -1));

        jBAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_ajustes_unp.png"))); // NOI18N
        jBAjustes.setActionCommand("AjustesMenu");
        jBAjustes.setContentAreaFilled(false);
        jBAjustes.setPreferredSize(new java.awt.Dimension(104, 114));
        jBAjustes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_ajustes_press.png"))); // NOI18N
        add(jBAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 136, -1, -1));

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_salir_unp.png"))); // NOI18N
        jBSalir.setActionCommand("SalirMenu");
        jBSalir.setContentAreaFilled(false);
        jBSalir.setPreferredSize(new java.awt.Dimension(104, 114));
        jBSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_salir_press.png"))); // NOI18N
        add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 136, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ventanas/ventana_menu.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAjustes;
    private javax.swing.JButton jBPlay;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBStats;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
