/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author Jason
 */
public class PanelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        jTNicKname.setBackground(new Color(0,0,0,0));
    }
   
    public String getJTNickName(){
       return jTNicKname.getText();
    }
    
    public void limpiar(){
        jTNicKname.setText("");
    }
 
    public void escuchar(ControladorPrincipal control){
        jBCheck.addActionListener(control);
        jBExit.addActionListener(control);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCheck = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jTNicKname = new javax.swing.JTextField();
        jLRegistro = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_check_unp.png"))); // NOI18N
        jBCheck.setActionCommand("CheckRegistro");
        jBCheck.setContentAreaFilled(false);
        jBCheck.setMinimumSize(new java.awt.Dimension(66, 76));
        jBCheck.setPreferredSize(new java.awt.Dimension(66, 70));
        jBCheck.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_check_press.png"))); // NOI18N
        add(jBCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 218, -1, -1));

        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_x_unp.png"))); // NOI18N
        jBExit.setActionCommand("SalirRegistro");
        jBExit.setContentAreaFilled(false);
        jBExit.setPreferredSize(new java.awt.Dimension(52, 56));
        jBExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_x_press.png"))); // NOI18N
        add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jTNicKname.setFont(new java.awt.Font("Milky Nice", 0, 28)); // NOI18N
        jTNicKname.setForeground(new java.awt.Color(145, 113, 49));
        jTNicKname.setBorder(null);
        jTNicKname.setPreferredSize(new java.awt.Dimension(64, 29));
        add(jTNicKname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 229, 370, 50));

        jLRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ventanas/ventana_registro.png"))); // NOI18N
        add(jLRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCheck;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLRegistro;
    private javax.swing.JTextField jTNicKname;
    // End of variables declaration//GEN-END:variables
}
