/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author Jason
 */
public class PanelGanador extends javax.swing.JPanel {

    /**
     * Creates new form PanelGanador
     */
    public PanelGanador() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }
    
    public void escuchar(ControladorPrincipal controlP){
        this.jBSalirGanador.addActionListener(controlP);
    }
    
    public void setJTNickNameG(String nickname, String puntaje){
        this.jLNickNameG.setText(nickname + " " + puntaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNickNameG = new javax.swing.JLabel();
        jBSalirGanador = new javax.swing.JButton();
        jLGanador = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNickNameG.setBackground(new java.awt.Color(191, 151, 64));
        jLNickNameG.setFont(new java.awt.Font("Milky Nice", 0, 46)); // NOI18N
        jLNickNameG.setForeground(new java.awt.Color(191, 151, 64));
        jLNickNameG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNickNameG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLNickNameG, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 520, 70));

        jBSalirGanador.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        jBSalirGanador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_siguiente_unp.png"))); // NOI18N
        jBSalirGanador.setActionCommand("SalirGanador");
        jBSalirGanador.setContentAreaFilled(false);
        jBSalirGanador.setPreferredSize(new java.awt.Dimension(144, 91));
        jBSalirGanador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_siguiente_press.png"))); // NOI18N
        add(jBSalirGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        jLGanador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ventanas/ventana_ganador.png"))); // NOI18N
        add(jLGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalirGanador;
    private javax.swing.JLabel jLGanador;
    private javax.swing.JLabel jLNickNameG;
    // End of variables declaration//GEN-END:variables
}
