package Vista;

import Controlador.ControladorNU;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jason
 */
public class PanelNU extends javax.swing.JPanel {

    private ControladorNU control;

    public PanelNU() {
        initComponents();
       
    }

    public void setControlador(ControladorNU control) {
        this.control = control;
    }

    public String getTiempo(){
        return jLCronometro.getText();
    }
   
    public String getNickname(){
        return jLNombreJugador.getText();
    }
  
    public String getJtPuntaje(){
        return jLPuntos.getText();
    }

    public void actualizarBarraVida(int vida) {
        switch (vida) {
            case 100:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_100.png"));
                break;

            case 90:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_90.png"));
                break;

            case 80:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_80.png"));
                break;

            case 70:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_70.png"));
                break;

            case 60:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_60.png"));
                break;

            case 50:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_50.png"));
                break;

            case 40:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_40.png"));
                break;

            case 30:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_30.png"));
                break;

            case 20:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_20.png"));
                break;

            case 10:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_10.png"));
                break;

            case 0:
                jLVida.setIcon(new ImageIcon("./src/main/resources/IMG/Iconos Munición y Vida/barra_vida_0.png"));
                break;
        }
    }          //AQUÍ QUEDÉ ---> SIGUE BUSCAR COMO ACTUALZIAR ESTO CON LA VIDA DE EL PERSONAJE PRINCIPAL

    public void actualizarMunicion(ImageIcon imagen) {
        jLIconoMunicion.setIcon(imagen);
    }

    public void actualizarNickName(String nickName) {
        if (nickName.equalsIgnoreCase("")) {
            jLNombreJugador.setText("Guest");
        } else {
            jLNombreJugador.setText(nickName);
        }
    }
    
    public void actualizarHoleadaexitosa(String texto) {
        jLWaveE.setText(texto);
    }
    
    public void actualizarHoleada(String texto) {
        jLWave.setText(texto);
    }

    public void actualizarTiempo(String tiempo) {
        jLCronometro.setText(tiempo);
    }
 
    public void actualizarPuntaje(int puntos) {
        jLPuntos.setText(String.valueOf(puntos) + " pts");
    }
  
    public void actializarConteoMunicion(String texto) {
        jLConteoMunicion.setText(texto);
    }
    
    public void escucharTeclas(ControladorNU control) {
        this.addKeyListener(control);
    }

      @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        control.dibujar(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLWaveE = new javax.swing.JLabel();
        jLWave = new javax.swing.JLabel();
        jLPuntos = new javax.swing.JLabel();
        jLNombreJugador = new javax.swing.JLabel();
        jLIconoPersonaje = new javax.swing.JLabel();
        jLBotonESC = new javax.swing.JLabel();
        jLVida = new javax.swing.JLabel();
        jLIconoVida = new javax.swing.JLabel();
        jLConteoMunicion = new javax.swing.JLabel();
        jLIconoMunicion = new javax.swing.JLabel();
        jLCronometro = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLWaveE.setFont(new java.awt.Font("Kid Games", 0, 70)); // NOI18N
        jLWaveE.setForeground(new java.awt.Color(255, 255, 255));
        jLWaveE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLWaveE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLWaveE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1920, 170));

        jLWave.setFont(new java.awt.Font("Kid Games", 0, 100)); // NOI18N
        jLWave.setForeground(new java.awt.Color(255, 255, 255));
        jLWave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLWave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLWave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1920, 170));

        jLPuntos.setFont(new java.awt.Font("Milky Nice", 0, 36)); // NOI18N
        jLPuntos.setForeground(new java.awt.Color(255, 255, 255));
        jLPuntos.setText("0 pts");
        add(jLPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, -1));

        jLNombreJugador.setFont(new java.awt.Font("Milky Nice", 0, 30)); // NOI18N
        jLNombreJugador.setForeground(new java.awt.Color(247, 208, 132));
        jLNombreJugador.setText("DefaultNickName");
        add(jLNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, -1));

        jLIconoPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconos Munición y Vida/icono_personaje.png"))); // NOI18N
        add(jLIconoPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLBotonESC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_esc_unp.png"))); // NOI18N
        add(jLBotonESC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 20, -1, -1));

        jLVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconos Munición y Vida/barra_vida_100.png"))); // NOI18N
        add(jLVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 38, -1, -1));

        jLIconoVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconos Munición y Vida/vida_icono.png"))); // NOI18N
        add(jLIconoVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 25, -1, -1));

        jLConteoMunicion.setFont(new java.awt.Font("Milky Nice Clean", 0, 48)); // NOI18N
        jLConteoMunicion.setForeground(new java.awt.Color(255, 255, 255));
        jLConteoMunicion.setText("X50");
        add(jLConteoMunicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 26, 130, -1));

        jLIconoMunicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Iconos Munición y Vida/municion_pesada_icono.png"))); // NOI18N
        add(jLIconoMunicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLCronometro.setFont(new java.awt.Font("Milky Nice", 1, 36)); // NOI18N
        jLCronometro.setForeground(new java.awt.Color(255, 255, 255));
        jLCronometro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLCronometro.setText("0:0");
        add(jLCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 20, 200, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Backgrounds/Background1.1.png"))); // NOI18N
        add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBotonESC;
    private javax.swing.JLabel jLConteoMunicion;
    private javax.swing.JLabel jLCronometro;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLIconoMunicion;
    private javax.swing.JLabel jLIconoPersonaje;
    private javax.swing.JLabel jLIconoVida;
    private javax.swing.JLabel jLNombreJugador;
    private javax.swing.JLabel jLPuntos;
    private javax.swing.JLabel jLVida;
    private javax.swing.JLabel jLWave;
    private javax.swing.JLabel jLWaveE;
    // End of variables declaration//GEN-END:variables
}
