/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author Jason
 */
public class PanelSalirN extends javax.swing.JPanel {

    /**
     * Creates new form PanelSalirN
     */
    public PanelSalirN() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }
    
    public void escuchar(ControladorPrincipal control){
        jBCheck.addActionListener(control);
        jBExit.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCheck = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jLSalir = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_check_unp.png"))); // NOI18N
        jBCheck.setActionCommand("CheckSalirNivel");
        jBCheck.setContentAreaFilled(false);
        jBCheck.setPreferredSize(new java.awt.Dimension(66, 70));
        jBCheck.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_check_press.png"))); // NOI18N
        add(jBCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_exitG_unp.png"))); // NOI18N
        jBExit.setActionCommand("ExitSalirNivel");
        jBExit.setContentAreaFilled(false);
        jBExit.setPreferredSize(new java.awt.Dimension(66, 70));
        jBExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_exitG_press.png"))); // NOI18N
        add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jLSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ventanas/ventana_salir_nivel.png"))); // NOI18N
        add(jLSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCheck;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLSalir;
    // End of variables declaration//GEN-END:variables
}
