/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author Jason
 */
public class PanelGameOver extends javax.swing.JPanel {
    private ControladorPrincipal controlP;

    /**
     * Creates new form PanelGameOver
     */
    public PanelGameOver() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }
    
    public void escuchar(ControladorPrincipal controlp){
        jBReinicio.addActionListener(controlp);
        jBSalirGO.addActionListener(controlp);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBReinicio = new javax.swing.JButton();
        jBSalirGO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBReinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_reinicio_unp.png"))); // NOI18N
        jBReinicio.setActionCommand("Reinicio");
        jBReinicio.setContentAreaFilled(false);
        jBReinicio.setPreferredSize(new java.awt.Dimension(70, 51));
        jBReinicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_reincio_press.png"))); // NOI18N
        add(jBReinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 382, -1, -1));

        jBSalirGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_salirGO_unp.png"))); // NOI18N
        jBSalirGO.setActionCommand("SalirGO");
        jBSalirGO.setContentAreaFilled(false);
        jBSalirGO.setPreferredSize(new java.awt.Dimension(70, 51));
        jBSalirGO.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_salirGO_press.png"))); // NOI18N
        add(jBSalirGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 382, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ventanas/ventana_gameover.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBReinicio;
    private javax.swing.JButton jBSalirGO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
