/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;

/**
 *
 * @author Jason
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    public void desactivarBotones(int numero) {
        if (numero == 1) {
            jBPlay.setEnabled(false);
            jBAjustes.setEnabled(true);
            jBInfo.setEnabled(true);
            jBSalir.setEnabled(true);
            jBStats.setEnabled(true);
        } else if (numero == 2) {
            jBPlay.setEnabled(true);
            jBAjustes.setEnabled(true);
            jBInfo.setEnabled(true);
            jBSalir.setEnabled(true);
            jBStats.setEnabled(false);
        } else if (numero == 3) {
            jBPlay.setEnabled(true);
            jBAjustes.setEnabled(true);
            jBInfo.setEnabled(false);
            jBSalir.setEnabled(true);
            jBStats.setEnabled(true);
        } else if (numero == 4) {
            jBPlay.setEnabled(true);
            jBAjustes.setEnabled(false);
            jBInfo.setEnabled(true);
            jBSalir.setEnabled(true);
            jBStats.setEnabled(true);
        } else if (numero == 5) {
            jBPlay.setEnabled(true);
            jBAjustes.setEnabled(true);
            jBInfo.setEnabled(true);
            jBSalir.setEnabled(false);
            jBStats.setEnabled(true);
        }
    }

    public void activarBotones() {
        jBPlay.setEnabled(true);
        jBAjustes.setEnabled(true);
        jBInfo.setEnabled(true);
        jBSalir.setEnabled(true);
        jBStats.setEnabled(true);
    }

    public void escuchar(ControladorPrincipal control) {
        jBAjustes.addActionListener(control);
        jBInfo.addActionListener(control);
        jBPlay.addActionListener(control);
        jBSalir.addActionListener(control);
        jBStats.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBPlay = new javax.swing.JButton();
        jBStats = new javax.swing.JButton();
        jBInfo = new javax.swing.JButton();
        jBAjustes = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_play_unp.png"))); // NOI18N
        jBPlay.setActionCommand("PlayPrincipal");
        jBPlay.setContentAreaFilled(false);
        jBPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_play_press.png"))); // NOI18N
        add(jBPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1775, 388, -1, -1));

        jBStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_estadisticas_unp.png"))); // NOI18N
        jBStats.setActionCommand("StatsPrincipal");
        jBStats.setContentAreaFilled(false);
        jBStats.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_estadisticas_press.png"))); // NOI18N
        add(jBStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(1775, 518, -1, -1));

        jBInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_info_unp.png"))); // NOI18N
        jBInfo.setActionCommand("Info");
        jBInfo.setContentAreaFilled(false);
        jBInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_info_press.png"))); // NOI18N
        add(jBInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1775, 648, -1, -1));

        jBAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_ajustes_unp.png"))); // NOI18N
        jBAjustes.setActionCommand("AjustesPrincipal");
        jBAjustes.setContentAreaFilled(false);
        jBAjustes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_ajustes_press.png"))); // NOI18N
        add(jBAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1775, 780, -1, -1));

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_salir_unp.png"))); // NOI18N
        jBSalir.setActionCommand("SalirPrincipal");
        jBSalir.setContentAreaFilled(false);
        jBSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_salir_press.png"))); // NOI18N
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1775, 910, -1, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Backgrounds/Background_Principal.png"))); // NOI18N
        add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAjustes;
    private javax.swing.JButton jBInfo;
    private javax.swing.JButton jBPlay;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBStats;
    private javax.swing.JLabel jLFondo;
    // End of variables declaration//GEN-END:variables
}
