/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;

/**
 *
 * @author Jason
 */
public class PanelPresentacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelPresentacion
     */
    public PanelPresentacion() {
        initComponents();
    }
    
    public void escuchar(ControladorPrincipal control){
        jBJugar.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBJugar = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_jugar_unp.png"))); // NOI18N
        jBJugar.setActionCommand("Jugar");
        jBJugar.setContentAreaFilled(false);
        jBJugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_jugar_press.png"))); // NOI18N
        add(jBJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 780, -1, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Backgrounds/Background_Presentacion.png"))); // NOI18N
        add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBJugar;
    private javax.swing.JLabel jLFondo;
    // End of variables declaration//GEN-END:variables
}
