/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import java.awt.Color;

/**
 *
 * @author Jason
 */
public class PanelAjustes extends javax.swing.JPanel {

    /**
     * Creates new form PanelAjustes
     */
    public PanelAjustes() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        jBUMMusica.setVisible(false);
        jBUMSonidos.setVisible(false);
    }

    public void mutearMusica() {
        jBMMusica.setVisible(false);
        jBUMMusica.setVisible(true);
    }

    public void desmutearMusica() {
        jBUMMusica.setVisible(false);
        jBMMusica.setVisible(true);
    }

    public void mutearSonidos() {
        jBMSonidos.setVisible(false);
        jBUMSonidos.setVisible(true);
    }

    public void desmutearSonidos() {
        jBUMSonidos.setVisible(false);
        jBMSonidos.setVisible(true);
    }

    public void setTVolumenMusica(String volumen) {
        this.jLVolMusica.setText(volumen);
    }

    public String getTVolumenMusica() {
        return this.jLVolMusica.getText();
    }

    public void setTVolumenSonido(String volumen) {
        this.jLVolSonidos.setText(volumen);
    }

    public String getTVolumenSonidos() {
        return this.jLVolSonidos.getText();
    }

    public void escuchar(ControladorPrincipal control) {
        jBExit.addActionListener(control);
        jBMMusica.addActionListener(control);
        jBMSonidos.addActionListener(control);
        jBUMMusica.addActionListener(control);
        jBUMSonidos.addActionListener(control);
        jBVDMusica.addActionListener(control);
        jBVDSonidos.addActionListener(control);
        jBVUMusica.addActionListener(control);
        jBVUSonidos.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLVolSonidos = new javax.swing.JLabel();
        jLVolMusica = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jBVUMusica = new javax.swing.JButton();
        jBVDMusica = new javax.swing.JButton();
        jBVUSonidos = new javax.swing.JButton();
        jBVDSonidos = new javax.swing.JButton();
        jBMMusica = new javax.swing.JButton();
        jBUMMusica = new javax.swing.JButton();
        jBMSonidos = new javax.swing.JButton();
        jBUMSonidos = new javax.swing.JButton();
        jLAjustes = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLVolSonidos.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        jLVolSonidos.setForeground(new java.awt.Color(145, 113, 49));
        jLVolSonidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLVolSonidos.setText("100");
        add(jLVolSonidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLVolMusica.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        jLVolMusica.setForeground(new java.awt.Color(145, 113, 49));
        jLVolMusica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLVolMusica.setText("100");
        add(jLVolMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 236, -1, -1));

        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_x_unp.png"))); // NOI18N
        jBExit.setActionCommand("SalirAjustes");
        jBExit.setContentAreaFilled(false);
        jBExit.setPreferredSize(new java.awt.Dimension(52, 56));
        jBExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_x_press.png"))); // NOI18N
        add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jBVUMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_up_unp.png"))); // NOI18N
        jBVUMusica.setActionCommand("VUMusica");
        jBVUMusica.setContentAreaFilled(false);
        jBVUMusica.setPreferredSize(new java.awt.Dimension(30, 24));
        jBVUMusica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_up_press.png"))); // NOI18N
        add(jBVUMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 217, -1, -1));

        jBVDMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_down_unp.png"))); // NOI18N
        jBVDMusica.setActionCommand("VDMusica");
        jBVDMusica.setContentAreaFilled(false);
        jBVDMusica.setPreferredSize(new java.awt.Dimension(30, 24));
        jBVDMusica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_down_press_1.png"))); // NOI18N
        add(jBVDMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jBVUSonidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_up_unp.png"))); // NOI18N
        jBVUSonidos.setActionCommand("VUSonidos");
        jBVUSonidos.setContentAreaFilled(false);
        jBVUSonidos.setPreferredSize(new java.awt.Dimension(30, 24));
        jBVUSonidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_up_press.png"))); // NOI18N
        add(jBVUSonidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 373, -1, -1));

        jBVDSonidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_down_unp.png"))); // NOI18N
        jBVDSonidos.setActionCommand("VDSonidos");
        jBVDSonidos.setContentAreaFilled(false);
        jBVDSonidos.setPreferredSize(new java.awt.Dimension(30, 24));
        jBVDSonidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_vol_down_press_1.png"))); // NOI18N
        add(jBVDSonidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 416, -1, -1));

        jBMMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_unmute_unp.png"))); // NOI18N
        jBMMusica.setActionCommand("MMusica");
        jBMMusica.setContentAreaFilled(false);
        jBMMusica.setMinimumSize(new java.awt.Dimension(52, 56));
        jBMMusica.setPreferredSize(new java.awt.Dimension(52, 56));
        jBMMusica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_unmute_press.png"))); // NOI18N
        add(jBMMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jBUMMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_mute_unp.png"))); // NOI18N
        jBUMMusica.setActionCommand("UMMusica");
        jBUMMusica.setContentAreaFilled(false);
        jBUMMusica.setPreferredSize(new java.awt.Dimension(52, 56));
        jBUMMusica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_mute_press.png"))); // NOI18N
        add(jBUMMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jBMSonidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_unmute_unp.png"))); // NOI18N
        jBMSonidos.setActionCommand("MSonidos");
        jBMSonidos.setContentAreaFilled(false);
        jBMSonidos.setMinimumSize(new java.awt.Dimension(52, 56));
        jBMSonidos.setPreferredSize(new java.awt.Dimension(52, 56));
        jBMSonidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_unmute_press.png"))); // NOI18N
        add(jBMSonidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jBUMSonidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_mute_unp.png"))); // NOI18N
        jBUMSonidos.setActionCommand("UMSonidos");
        jBUMSonidos.setContentAreaFilled(false);
        jBUMSonidos.setPreferredSize(new java.awt.Dimension(52, 56));
        jBUMSonidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_mute_press.png"))); // NOI18N
        add(jBUMSonidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ventanas/ventana_ajustes.png"))); // NOI18N
        add(jLAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBMMusica;
    private javax.swing.JButton jBMSonidos;
    private javax.swing.JButton jBUMMusica;
    private javax.swing.JButton jBUMSonidos;
    private javax.swing.JButton jBVDMusica;
    private javax.swing.JButton jBVDSonidos;
    private javax.swing.JButton jBVUMusica;
    private javax.swing.JButton jBVUSonidos;
    private javax.swing.JLabel jLAjustes;
    private javax.swing.JLabel jLVolMusica;
    private javax.swing.JLabel jLVolSonidos;
    // End of variables declaration//GEN-END:variables
}
