/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.GestionCeldas;
import Modelo.GestionEncabezadoTabla;
import Controlador.ControladorPrincipal;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Jason
 */
public class PanelStats extends javax.swing.JPanel {

    private TableModel modelo;

    private int filasTabla;
    private int columnasTabla;

    /**
     * Creates new form PanelStats
     */
    public PanelStats() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        jScrollPane1.setBackground(new Color(191,151,64));
        jtbStats.setBackground(new Color(191,151,64));
    }

    public void setDatosTabla(String[][] datos, String[] etiquetas) {
        modelo = new  DefaultTableModel(datos, etiquetas);
        jtbStats.setModel(modelo);

        filasTabla = jtbStats.getRowCount();
        columnasTabla = jtbStats.getColumnCount();
        
        jtbStats.getColumnModel().getColumn(0).setCellRenderer(new GestionCeldas("texto"));
        jtbStats.getColumnModel().getColumn(1).setCellRenderer(new GestionCeldas("texto"));
        jtbStats.getColumnModel().getColumn(2).setCellRenderer(new GestionCeldas("numerico"));
        jtbStats.getColumnModel().getColumn(3).setCellRenderer(new GestionCeldas("numerico"));
        jtbStats.getColumnModel().getColumn(4).setCellRenderer(new GestionCeldas("numerico"));
        jtbStats.getColumnModel().getColumn(5).setCellRenderer(new GestionCeldas("numerico"));

        jtbStats.getTableHeader().setReorderingAllowed(false);
        jtbStats.setRowHeight(50);
        jtbStats.setGridColor(new Color(191,151,64));

        JTableHeader jtableHeader = jtbStats.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        jtbStats.setTableHeader(jtableHeader);

        jScrollPane1.setViewportView(this.jtbStats);
    }
    
    public void escuchar(ControladorPrincipal control) {
        jBDelete.addActionListener(control);
        jBExit.addActionListener(control);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbStats = new javax.swing.JTable();
        jBDelete = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jLStats = new javax.swing.JLabel();

        setForeground(new java.awt.Color(145, 113, 49));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbStats.setBackground(new java.awt.Color(191, 151, 64));
        jtbStats.setFont(new java.awt.Font("Milky Nice Clean", 0, 18)); // NOI18N
        jtbStats.setForeground(new java.awt.Color(145, 113, 49));
        jtbStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Duracion", "Puntaje", "Balas", "Enemigos"
            }
        ));
        jtbStats.setToolTipText("");
        jtbStats.setAutoscrolls(false);
        jtbStats.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtbStats.setDragEnabled(true);
        jtbStats.setEnabled(false);
        jtbStats.setFillsViewportHeight(true);
        jtbStats.setGridColor(new java.awt.Color(191, 151, 64));
        jtbStats.setSelectionBackground(new java.awt.Color(191, 151, 64));
        jtbStats.setSelectionForeground(new java.awt.Color(145, 113, 49));
        jtbStats.setShowGrid(false);
        jScrollPane1.setViewportView(jtbStats);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 187, 860, 450));

        jBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_delete_unp.png"))); // NOI18N
        jBDelete.setActionCommand("DeleteStats");
        jBDelete.setContentAreaFilled(false);
        jBDelete.setPreferredSize(new java.awt.Dimension(66, 70));
        jBDelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_delete_press.png"))); // NOI18N
        add(jBDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_x_unp.png"))); // NOI18N
        jBExit.setActionCommand("ExitStats");
        jBExit.setContentAreaFilled(false);
        jBExit.setPreferredSize(new java.awt.Dimension(52, 56));
        jBExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/boton_x_press.png"))); // NOI18N
        add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, -1, -1));

        jLStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Ventanas/ventana_estadisticas.png"))); // NOI18N
        add(jLStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLStats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbStats;
    // End of variables declaration//GEN-END:variables
}
